name: Output events on issues
on: 
    issues:
        types: opened
jobs:
    Output-context:
        runs-on: ubuntu-latest
        steps:
        - name: output
          run: echo "${{ toJson(github.event) }}"
